version: 2.1

defaults: &defaults
  working_directory: ~/repo
  resource_class: medium
  machine:
    image: ubuntu-2004:202107-02

jobs:
  continuous_integration:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - run:
          name: Build project
          command: yarn build
      - run:
          name: Run tests
          command: yarn test-ci
      - run:
          name: Lint project
          command: yarn lint
      - run:
          name: Check types
          command: yarn check-types
      - run:
          name: Deploy to S3
          command: echo "Deployment should be here"

workflows:
  ci_cd:
    jobs:
      - continuous_integration
